### ISSUE TITLE
Most of function nodes are giving error on loading the example workflow.json

### ISSUE THREAD

**Issue by jags111** [Derfuu/Derfuu_ComfyUI_ModdedNodes#10]
I tried several times to reinstall and check on the nodes and it is failing to load most of the functions. Not sure where the break is happening. Here is the screen shot and kindly update what is being missed. Thanks
<img width="1280" alt="Derfuu" src="https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes/assets/5968619/462324a7-fa1a-4e18-ae16-cdce18b716ba">

**Comment by Derfuu** [comment]
i don't know how did you got that type of error, but сan you explain what you did to get this error or send log. Tried myself load exapmle from repo - it works normally.

Maybie it was fixed with last commit of comfy? ~12h ago (https://github.com/comfyanonymous/ComfyUI/commit/1938f5c5fe479996802c46d5c2233887e3598a40)

Also i don't remember that last versions of ComfyUI got this side or bottom menu.

**Comment by jags111** [comment]
okay one more time will reload the same and update again

**Comment by jags111** [comment]
can you update the js script for these nodes as it may help locate the nodes in comfyUI... as every time it is giving this error
Cannot import D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes module for custom nodes: No module named 'custom_nodes.Derfuu_ComfyUI_ModdedNodes'
